apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_name: cG9zdGdyZXM=
  db_user: cG9zdGdyZXMubGNpdXluamttYmZ3bWd0emtpaW0=
  db_password: VWJ3d0lFNmE3bFd3bnFxZA==
  db_port: NjU0Mw==
  db_host: YXdzLTAtdXMtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=